// src/utils/generateExamReport.js
// Generates a professional PDF report suitable for employer presentation
import jsPDF from 'jspdf';

// ─── Brand colours ────────────────────────────────────────────────────────────
const C = {
  primary:    [37, 99, 235],   // blue-600
  primaryDk:  [30, 64, 175],   // blue-800
  accent:     [16, 185, 129],  // emerald-500
  accentDk:   [5, 150, 105],   // emerald-600
  danger:     [220, 38, 38],   // red-600
  dangerLight:[254, 226, 226], // red-100
  passLight:  [209, 250, 229], // emerald-100
  gray50:     [249, 250, 251],
  gray100:    [243, 244, 246],
  gray200:    [229, 231, 235],
  gray400:    [156, 163, 175],
  gray600:    [75, 85, 99],
  gray700:    [55, 65, 81],
  gray800:    [31, 41, 55],
  gray900:    [17, 24, 39],
  white:      [255, 255, 255],
};

const PW = 210; // A4 page width mm
const PH = 297; // A4 page height mm
const ML = 20;  // margin left
const MR = 20;  // margin right
const CW = PW - ML - MR; // content width

function rgb(doc, color) { doc.setTextColor(...color); }
function fill(doc, color) { doc.setFillColor(...color); }
function stroke(doc, color) { doc.setDrawColor(...color); }

function drawRect(doc, x, y, w, h, fillColor, strokeColor, r = 0) {
  if (fillColor) { fill(doc, fillColor); }
  if (strokeColor) { stroke(doc, strokeColor); } else { doc.setDrawColor(0, 0, 0, 0); }
  if (r > 0) { doc.roundedRect(x, y, w, h, r, r, fillColor ? (strokeColor ? 'FD' : 'F') : 'S'); }
  else { doc.rect(x, y, w, h, fillColor ? (strokeColor ? 'FD' : 'F') : 'S'); }
}

function bold(doc) { doc.setFont('helvetica', 'bold'); }
function regular(doc) { doc.setFont('helvetica', 'normal'); }
function italic(doc) { doc.setFont('helvetica', 'italic'); }

function addPage(doc) {
  doc.addPage('a4');
  return PH - 20; // bottom margin
}

// ─── Header band on every page ────────────────────────────────────────────────
function drawHeader(doc, pageNum) {
  // Blue gradient band
  drawRect(doc, 0, 0, PW, 22, C.primary);
  drawRect(doc, 0, 18, PW, 4, C.primaryDk);

  // Logo mark (C letter in circle)
  fill(doc, C.white); stroke(doc, [255,255,255,0]);
  doc.circle(ML + 6, 11, 6, 'F');
  rgb(doc, C.primary);
  bold(doc); doc.setFontSize(10);
  doc.text('C', ML + 6, 11 + 3.5, { align: 'center' });

  // Brand name
  rgb(doc, C.white);
  bold(doc); doc.setFontSize(13);
  doc.text('CertiPractice', ML + 14, 12.5);
  regular(doc); doc.setFontSize(8);
  doc.text('Professional Skills Assessment', ML + 14, 17);

  // Page number
  rgb(doc, [200, 220, 255]);
  regular(doc); doc.setFontSize(8);
  doc.text(`Page ${pageNum}`, PW - MR, 12.5, { align: 'right' });
}

// ─── Footer on every page ─────────────────────────────────────────────────────
function drawFooter(doc) {
  const y = PH - 12;
  drawRect(doc, 0, y - 2, PW, 14, C.gray50);
  stroke(doc, C.gray200); doc.line(0, y - 2, PW, y - 2);

  rgb(doc, C.gray400); regular(doc); doc.setFontSize(7);
  doc.text(
    'This report was generated by CertiPractice (certipractice.vercel.app) and reflects performance on a practice exam.',
    ML, y + 2
  );
  doc.text(
    `Generated: ${new Date().toLocaleString('en-GB')}  |  Report ID: CP-${Date.now().toString(36).toUpperCase()}`,
    ML, y + 6
  );
  rgb(doc, C.primary);
  doc.text('certipractice.vercel.app', PW - MR, y + 4, { align: 'right' });
}

// ─── Section heading ─────────────────────────────────────────────────────────
function sectionTitle(doc, text, y) {
  drawRect(doc, ML, y, CW, 8, C.primary, null, 2);
  rgb(doc, C.white); bold(doc); doc.setFontSize(9.5);
  doc.text(text.toUpperCase(), ML + 4, y + 5.5);
  return y + 12;
}

// ─── Stat box ─────────────────────────────────────────────────────────────────
function statBox(doc, x, y, w, h, label, value, sub, accent) {
  drawRect(doc, x, y, w, h, C.white, C.gray200, 3);
  // Left accent bar
  drawRect(doc, x, y, 3, h, accent || C.primary, null, 0);

  bold(doc); doc.setFontSize(18); rgb(doc, accent || C.primary);
  doc.text(String(value), x + w / 2, y + h / 2 - 1, { align: 'center' });
  regular(doc); doc.setFontSize(7.5); rgb(doc, C.gray600);
  doc.text(label, x + w / 2, y + h - 5, { align: 'center' });
  if (sub) {
    italic(doc); doc.setFontSize(6.5); rgb(doc, C.gray400);
    doc.text(sub, x + w / 2, y + h - 1, { align: 'center' });
  }
}

// ─── Horizontal bar ──────────────────────────────────────────────────────────
function progressBar(doc, x, y, w, pct, color) {
  drawRect(doc, x, y, w, 5, C.gray100, C.gray200, 2);
  if (pct > 0) {
    drawRect(doc, x, y, Math.max(w * pct / 100, 3), 5, color || C.primary, null, 2);
  }
}

// ─── Main generator ───────────────────────────────────────────────────────────
export function generateExamReport({ exam, results, user, lang = 'en' }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  doc.setFont('helvetica');

  const T = {
    reportTitle:    lang === 'es' ? 'INFORME DE EVALUACIÓN PROFESIONAL' : 'PROFESSIONAL SKILLS ASSESSMENT REPORT',
    subtitle:       lang === 'es' ? 'Evaluación de preparación para certificación' : 'Certification Readiness Assessment',
    candidateInfo:  lang === 'es' ? '1. Información del Candidato' : '1. Candidate Information',
    examDetails:    lang === 'es' ? '2. Detalles del Examen' : '2. Exam Details',
    resultsSummary: lang === 'es' ? '3. Resumen de Resultados' : '3. Results Summary',
    perfAnalysis:   lang === 'es' ? '4. Análisis de Rendimiento' : '4. Performance Analysis',
    validation:     lang === 'es' ? '5. Declaración de Validación' : '5. Validation Statement',
    recommendation: lang === 'es' ? '6. Recomendación' : '6. Recommendation',
    name:     lang === 'es' ? 'Nombre:' : 'Name:',
    date:     lang === 'es' ? 'Fecha:' : 'Date:',
    reportId: lang === 'es' ? 'ID de Informe:' : 'Report ID:',
    provider: lang === 'es' ? 'Proveedor:' : 'Provider:',
    cert:     lang === 'es' ? 'Certificación:' : 'Certification:',
    mode:     lang === 'es' ? 'Modo:' : 'Mode:',
    total:    lang === 'es' ? 'Total Preguntas:' : 'Total Questions:',
    time:     lang === 'es' ? 'Tiempo Utilizado:' : 'Time Used:',
    passing:  lang === 'es' ? 'Nota de Corte:' : 'Passing Score:',
    score:    lang === 'es' ? 'Puntuación' : 'Score',
    correct:  lang === 'es' ? 'Correctas' : 'Correct',
    wrong:    lang === 'es' ? 'Incorrectas' : 'Incorrect',
    skipped:  lang === 'es' ? 'Sin Responder' : 'Unanswered',
    passed:   lang === 'es' ? '✓ APROBADO' : '✓ PASSED',
    failed:   lang === 'es' ? '✗ NO APROBADO' : '✗ NOT PASSED',
    validText: lang === 'es'
      ? 'Este documento certifica que el candidato identificado anteriormente ha completado satisfactoriamente una evaluación de práctica para la certificación indicada en la plataforma CertiPractice. Los resultados reflejan el rendimiento en las preguntas de práctica y sirven como indicador del nivel de preparación del candidato para el examen oficial.'
      : 'This document certifies that the above-named candidate has successfully completed a practice assessment for the indicated certification on the CertiPractice platform. The results reflect performance on practice questions and serve as an indicator of the candidate\'s readiness level for the official examination.',
    recPassed: lang === 'es'
      ? 'El candidato demuestra un nivel de conocimiento superior al mínimo requerido para la certificación. Se recomienda proceder con la inscripción al examen oficial.'
      : 'The candidate demonstrates a knowledge level exceeding the minimum required for certification. It is recommended to proceed with registration for the official examination.',
    recFailed: lang === 'es'
      ? 'El candidato ha completado la evaluación de práctica. Se recomienda continuar con el estudio enfocado en las áreas de menor rendimiento antes de presentar el examen oficial.'
      : 'The candidate has completed the practice assessment. It is recommended to continue focused study in lower-performing areas before sitting the official examination.',
    prepLevel: lang === 'es' ? 'Nivel de Preparación' : 'Preparation Level',
    minReq:    lang === 'es' ? 'Mínimo Requerido' : 'Minimum Required',
    yourScore: lang === 'es' ? 'Tu Puntuación' : 'Your Score',
    employer:  lang === 'es' ? 'Para Empleadores / Managers' : 'For Employers / Managers',
    employerNote: lang === 'es'
      ? 'CertiPractice es una plataforma de preparación para certificaciones cloud que cuenta con una biblioteca de preguntas de práctica curada por expertos. Este informe puede ser presentado como evidencia del esfuerzo de preparación del candidato y su nivel de conocimiento previo al examen oficial.'
      : 'CertiPractice is a cloud certification preparation platform featuring a library of expert-curated practice questions. This report may be presented as evidence of the candidate\'s preparation effort and knowledge level prior to the official examination.',
  };

  const summary = results?.examSummary || results || {};
  const score = summary.score ?? 0;
  const passed = summary.passed ?? score >= (exam?.passingScore || 70);
  const passingScore = exam?.passingScore || summary.passingScore || 70;
  const totalQ = summary.totalQuestions || exam?.questions?.length || 0;
  const correctQ = summary.correctAnswers ?? Math.round(totalQ * score / 100);
  const incorrectQ = summary.incorrectAnswers ?? (totalQ - correctQ);
  const unansweredQ = Math.max(0, totalQ - correctQ - incorrectQ);
  const timeUsed = summary.timeSpent
    ? `${Math.floor(summary.timeSpent / 60)}m ${summary.timeSpent % 60}s`
    : (lang === 'es' ? 'No registrado' : 'Not recorded');
  const reportId = `CP-${Date.now().toString(36).toUpperCase()}`;
  const dateStr = new Date().toLocaleDateString(lang === 'es' ? 'es-ES' : 'en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  const candidateName = user ? `${user.firstName || ''} ${user.lastName || ''}`.trim() || user.username : (lang === 'es' ? 'Usuario Invitado' : 'Guest User');
  const modeLabel = exam?.examMode === 'realistic' ? (lang === 'es' ? 'Simulación Real' : 'Real Simulation') : exam?.examMode === 'failed_questions' ? (lang === 'es' ? 'Preguntas Fallidas' : 'Failed Questions') : (lang === 'es' ? 'Modo Práctica' : 'Practice Mode');

  // ── PAGE 1 ──────────────────────────────────────────────────────────────────
  let page = 1;
  drawHeader(doc, page);
  drawFooter(doc);

  let y = 30;

  // ── Report title block ────────────────────────────────────────────────────
  drawRect(doc, ML, y, CW, 28, C.gray50, C.gray200, 4);
  drawRect(doc, ML, y, 4, 28, passed ? C.accent : C.danger, null, 0);

  bold(doc); doc.setFontSize(15); rgb(doc, C.gray900);
  doc.text(T.reportTitle, ML + 10, y + 10);
  regular(doc); doc.setFontSize(9.5); rgb(doc, C.gray600);
  doc.text(T.subtitle, ML + 10, y + 17);

  // Pass / Fail badge
  const badgeColor = passed ? C.accent : C.danger;
  const badgeLight = passed ? C.passLight : C.dangerLight;
  drawRect(doc, PW - MR - 38, y + 5, 36, 14, badgeLight, badgeColor, 3);
  bold(doc); doc.setFontSize(10); rgb(doc, badgeColor);
  doc.text(passed ? T.passed : T.failed, PW - MR - 38 + 18, y + 14, { align: 'center' });

  y += 34;

  // ── 1. Candidate info ─────────────────────────────────────────────────────
  y = sectionTitle(doc, T.candidateInfo, y);

  const col1x = ML, col2x = ML + CW / 2 + 5, hw = CW / 2 - 5;

  // Row: Name | Date
  drawRect(doc, col1x, y, hw, 12, C.white, C.gray100, 2);
  drawRect(doc, col2x, y, hw, 12, C.white, C.gray100, 2);
  bold(doc); doc.setFontSize(8); rgb(doc, C.gray500 || C.gray400);
  doc.text(T.name, col1x + 4, y + 4.5);
  doc.text(T.date, col2x + 4, y + 4.5);
  regular(doc); doc.setFontSize(9); rgb(doc, C.gray900);
  doc.text(candidateName, col1x + 4, y + 9.5);
  doc.text(dateStr, col2x + 4, y + 9.5);
  y += 16;

  // Row: Email | Report ID
  drawRect(doc, col1x, y, hw, 12, C.white, C.gray100, 2);
  drawRect(doc, col2x, y, hw, 12, C.white, C.gray100, 2);
  bold(doc); doc.setFontSize(8); rgb(doc, C.gray400);
  doc.text('Email:', col1x + 4, y + 4.5);
  doc.text(T.reportId, col2x + 4, y + 4.5);
  regular(doc); doc.setFontSize(9); rgb(doc, C.gray900);
  doc.text(user?.email || '—', col1x + 4, y + 9.5);
  doc.text(reportId, col2x + 4, y + 9.5);
  y += 18;

  // ── 2. Exam details ───────────────────────────────────────────────────────
  y = sectionTitle(doc, T.examDetails, y);

  const details = [
    [T.provider, exam?.provider || '—'],
    [T.cert, `${exam?.certification || '—'} ${exam?.certificationCode ? `(${exam.certificationCode})` : ''}`.trim()],
    [T.mode, modeLabel],
    [T.total, `${totalQ} questions`],
    [T.passing, `${passingScore}%`],
    [T.time, timeUsed],
  ];

  const detailColW = CW / 3 - 2;
  details.forEach(([label, value], i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const dx = ML + col * (detailColW + 3);
    const dy = y + row * 16;
    drawRect(doc, dx, dy, detailColW, 13, C.white, C.gray100, 2);
    bold(doc); doc.setFontSize(7.5); rgb(doc, C.gray400);
    doc.text(label, dx + 4, dy + 4.5);
    regular(doc); doc.setFontSize(9); rgb(doc, C.gray800);
    doc.text(String(value), dx + 4, dy + 10, { maxWidth: detailColW - 8 });
  });

  y += Math.ceil(details.length / 3) * 16 + 6;

  // ── 3. Results summary ────────────────────────────────────────────────────
  y = sectionTitle(doc, T.resultsSummary, y);

  const boxW = (CW - 6) / 4;
  statBox(doc, ML,                  y, boxW, 28, T.score, `${score}%`, `/ 100%`, passed ? C.accent : C.danger);
  statBox(doc, ML + boxW + 2,       y, boxW, 28, T.correct, correctQ, `${totalQ > 0 ? Math.round(correctQ/totalQ*100) : 0}%`, C.accent);
  statBox(doc, ML + (boxW + 2) * 2, y, boxW, 28, T.wrong, incorrectQ, `${totalQ > 0 ? Math.round(incorrectQ/totalQ*100) : 0}%`, C.danger);
  statBox(doc, ML + (boxW + 2) * 3, y, boxW, 28, T.skipped, unansweredQ, ' ', C.gray400);
  y += 32;

  // ── 4. Performance analysis ───────────────────────────────────────────────
  y = sectionTitle(doc, T.perfAnalysis, y);

  // Score gauge visual
  const barY = y + 2;

  // Passing score line
  const barW = CW;
  drawRect(doc, ML, barY, barW, 12, C.gray100, C.gray200, 3);

  // Fill to score
  const fillW = Math.max((score / 100) * barW, 3);
  drawRect(doc, ML, barY, fillW, 12, passed ? C.accent : C.danger, null, 3);

  // Passing score marker
  const markerX = ML + (passingScore / 100) * barW;
  stroke(doc, C.gray600); doc.setLineWidth(0.5);
  doc.line(markerX, barY - 1, markerX, barY + 14);
  bold(doc); doc.setFontSize(7); rgb(doc, C.gray600);
  doc.text(`${passingScore}% min`, markerX + 1, barY + 18);

  // Score label inside bar
  rgb(doc, C.white); bold(doc); doc.setFontSize(8);
  doc.text(`${score}%`, ML + Math.min(fillW, barW) - 6, barY + 7.5, { align: 'right' });

  y += 22;

  // Mini stat rows
  const statRows = [
    { label: T.yourScore, pct: score, color: passed ? C.accent : C.danger },
    { label: T.minReq, pct: passingScore, color: C.gray400 },
  ];
  statRows.forEach(({ label, pct, color }) => {
    bold(doc); doc.setFontSize(8); rgb(doc, C.gray700);
    doc.text(label, ML, y + 4);
    progressBar(doc, ML + 40, y, CW - 50, pct, color);
    regular(doc); doc.setFontSize(8); rgb(doc, C.gray700);
    doc.text(`${pct}%`, PW - MR, y + 4, { align: 'right' });
    y += 9;
  });

  y += 4;

  // ── 5. Validation statement ───────────────────────────────────────────────
  y = sectionTitle(doc, T.validation, y);

  drawRect(doc, ML, y, CW, 26, C.gray50, C.gray200, 3);
  drawRect(doc, ML, y, 3, 26, C.primary, null, 0);
  regular(doc); doc.setFontSize(8.5); rgb(doc, C.gray700);
  const validLines = doc.splitTextToSize(T.validText, CW - 12);
  doc.text(validLines, ML + 7, y + 6);
  y += 31;

  // ── 6. Recommendation ────────────────────────────────────────────────────
  y = sectionTitle(doc, T.recommendation, y);

  const recColor = passed ? C.passLight : C.dangerLight;
  const recBorder = passed ? C.accent : C.danger;
  drawRect(doc, ML, y, CW, 22, recColor, recBorder, 3);
  bold(doc); doc.setFontSize(9); rgb(doc, passed ? C.accentDk : C.danger);
  doc.text(passed ? '✓' : '!', ML + 6, y + 10);
  regular(doc); doc.setFontSize(8.5); rgb(doc, C.gray800);
  const recLines = doc.splitTextToSize(passed ? T.recPassed : T.recFailed, CW - 18);
  doc.text(recLines, ML + 14, y + 7);
  y += 28;

  // ── Employer note ─────────────────────────────────────────────────────────
  drawRect(doc, ML, y, CW, 28, [239, 246, 255], C.primary, 3);
  drawRect(doc, ML, y, 3, 28, C.primary, null, 0);
  bold(doc); doc.setFontSize(8.5); rgb(doc, C.primaryDk);
  doc.text(`ℹ ${T.employer}`, ML + 7, y + 6);
  regular(doc); doc.setFontSize(8); rgb(doc, C.gray700);
  const empLines = doc.splitTextToSize(T.employerNote, CW - 12);
  doc.text(empLines, ML + 7, y + 12);

  // ── Save ─────────────────────────────────────────────────────────────────
  const certCode = exam?.certificationCode || exam?.certification || 'exam';
  const filename = `CertiPractice_Report_${certCode}_${new Date().toISOString().slice(0,10)}.pdf`;
  doc.save(filename);
  return filename;
}
